r"""results.json -> report/generated/values.tex  (one LaTeX macro per number).

Macro name:  \valKey  (snake_case key -> CamelCase).  e.g. pump_psi_meas -> \valPumpPsiMeas
Body uses siunitx so units and uncertainties format consistently:
    unit + unc:  \qty{1.10 +- 0.05}{\percent}
    unit only :  \qty{95}{\milli\meter}
    no unit, unc: \num{1.10 +- 0.05}
    no unit    :  \num{19}
    string val :  emitted verbatim (for text labels)

Preamble needs:  \usepackage{siunitx}   (and \DeclareSIUnit\rpm{rpm} if you use rpm).
Then in prose:   "...the measured head coefficient is \valPumpPsiMeas, ..."

    python export_latex.py
"""
from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
JSON = HERE.parent.parent / "report" / "generated" / "results.json"
TEX = HERE.parent.parent / "report" / "generated" / "values.tex"


_DIGIT_WORDS = {
    "0": "Zero", "1": "One", "2": "Two", "3": "Three", "4": "Four",
    "5": "Five", "6": "Six", "7": "Seven", "8": "Eight", "9": "Nine",
}


def macro_name(key: str) -> str:
    # TeX control-sequence names are letters only; spell out any digits so
    # keys like pump_b2 / turb_p01_design produce valid macros (\valPumpBTwo).
    camel = "".join(p.capitalize() for p in key.split("_"))
    return "val" + "".join(_DIGIT_WORDS.get(c, c) for c in camel)


def _num(x, fmt: str) -> str:
    return format(x, fmt) if isinstance(x, (int, float)) else str(x)


def emit(v: dict) -> str:
    val, unit, unc, fmt = v["val"], v.get("unit", ""), v.get("unc"), v.get("fmt", "g")
    if isinstance(val, str):
        return rf"{val}\xspace"  # verbatim text label
    body = _num(val, fmt)
    if unc is not None:
        body = f"{body} +- {_num(unc, fmt)}"
    return rf"\qty{{{body}}}{{{unit}}}\xspace" if unit else rf"\num{{{body}}}\xspace"


def main():
    data = json.loads(JSON.read_text(encoding="utf-8"))
    lines = [
        "% AUTO-GENERATED by export_latex.py — DO NOT EDIT BY HAND.",
        "% Regenerate:  python build_values.py && python export_latex.py",
        r"% Requires \usepackage{siunitx} and \usepackage{xspace} in the preamble.",
        "",
    ]
    for key, v in sorted(data.items()):
        lines.append(rf"\newcommand{{\{macro_name(key)}}}{{{emit(v)}}}  % {v.get('desc','')}")
    TEX.parent.mkdir(parents=True, exist_ok=True)
    TEX.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {TEX}  ({len(data)} macros)")


if __name__ == "__main__":
    main()
